-- --------------------------------------------------------
-- 4. Tags (タグマスタ)
-- "#海外旅行" などのタグ名そのものを管理
-- 公式フラグを追加し、検索サジェストの優先度制御などに利用
-- --------------------------------------------------------

create table public.tags (
  id bigint generated by default as identity primary key,
  
  -- タグ名 (重複禁止)
  name text not null unique,
  
  -- 使用回数 (人気順ソート用)
  usage_count integer default 0,
  
  -- ★追加: 公式フラグ
  -- true: 運営が用意した推奨タグ (サジェストで優先表示など)
  -- false: ユーザーが勝手に作ったタグ
  is_official boolean default false not null,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- --------------------------------------------------------
-- インデックス設定
-- --------------------------------------------------------
-- 公式タグのみを高速にフィルタリングする用
create index idx_tags_is_official on public.tags(is_official);

-- 人気順ソート用
create index idx_tags_usage_count on public.tags(usage_count desc);


-- --------------------------------------------------------
-- RLS (Row Level Security) 設定
-- --------------------------------------------------------
alter table public.tags enable row level security;

-- 閲覧: 全員OK
create policy "Tags are viewable by everyone"
  on public.tags for select using (true);

-- 作成: ログインユーザーなら新しいタグを作って良い
-- (UIからの作成時はデフォルトで is_official = false になる)
create policy "Authenticated users can create tags"
  on public.tags for insert with check (auth.role() = 'authenticated');