-- --------------------------------------------------------
-- Achievements (実績) テーブル
-- カテゴリ: 5種固定
-- 難易度: S〜E
-- 目安時間: day, week, month, year, over
-- --------------------------------------------------------

create table public.achievements (
  id bigint generated by default as identity primary key,
  
  -- カテゴリ (5種固定)
  category text not null check (category in ('INT', 'WLT', 'VIT', 'SOC', 'EXP')),
  
  -- 管理用コード (公式: 'INT_EIKEN_1' / UGC: NULL)
  code text unique,
  
  title text not null,
  description text,
  base_points integer not null default 10,
  
  -- 難易度ランク (easy, normal, hard, unmeasurable)
  difficulty text not null default 'unmeasurable' check (difficulty in ('easy', 'normal', 'hard', 'unmeasurable')),
  
  -- 目安時間 (指定の5パターンのみ許可)
  -- day   : 数時間〜1日以内
  -- week  : 数日〜1週間
  -- month : 数週間〜1ヶ月
  -- year  : 数ヶ月〜1年
  -- over  : 1年以上〜生涯
  estimated_time text check (estimated_time in ('day', 'week', 'month', 'year', 'over')),
  
  -- アイコン (画像のパス または アイコン名)
  icon_path text,
  
  is_official boolean default false not null,
  created_by uuid references auth.users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- --------------------------------------------------------
-- インデックス & RLS
-- --------------------------------------------------------
create index idx_achievements_category on public.achievements(category);
create index idx_achievements_difficulty on public.achievements(difficulty);
create index idx_achievements_time on public.achievements(estimated_time); -- 時間で絞り込み用
create index idx_achievements_is_official on public.achievements(is_official);

alter table public.achievements enable row level security;

-- 閲覧ポリシー
create policy "Achievements are viewable by everyone"
  on public.achievements for select using (true);

-- 作成ポリシー (ログイン必須)
create policy "Authenticated users can create achievements"
  on public.achievements for insert with check (auth.role() = 'authenticated');