-- --------------------------------------------------------
-- 3. Unlocks (実績解除・進捗)
-- --------------------------------------------------------

create table public.unlocks (
  id bigint generated by default as identity primary key,

  -- 誰が (Supabase AuthのUID)
  user_id uuid references auth.users(id) on delete cascade not null,

  -- 何を (実績ID)
  achievement_id bigint references public.achievements(id) on delete cascade not null,

  -- 状態
  -- CHALLENGING: 挑戦中 (リストに追加済み)
  -- DROPPED:     中断 (やったけど辞めた)
  -- COMPLETED:   達成 (自己申告で完了)
  status text not null default 'CHALLENGING'
    check (status in ('CHALLENGING', 'DROPPED', 'COMPLETED')),

  -- 達成日時
  -- COMPLETEDになったら現在時刻を入れる。それ以外はNULL
  unlocked_at timestamp with time zone,

  -- 作成日時 (挑戦開始日)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- 制約: 1つの実績に対して1つのレコードしか持てない
  unique(user_id, achievement_id)
);

-- --------------------------------------------------------
-- インデックス設定
-- --------------------------------------------------------
create index idx_unlocks_user_id on public.unlocks(user_id);
create index idx_unlocks_achievement_id on public.unlocks(achievement_id);
create index idx_unlocks_status on public.unlocks(status);


-- --------------------------------------------------------
-- RLS (Row Level Security) 設定
-- --------------------------------------------------------
alter table public.unlocks enable row level security;

-- ■ ポリシー1: 閲覧 (SELECT)
-- 以下のどちらかなら見れる
-- A. 自分のデータである (auth.uid() = user_id)
-- B. そのデータの実所有者のプロフィールが「公開(is_public=true)」になっている
--    (profiles_view は使わず、直接 profiles テーブルの公開フラグを参照する)
create policy "Unlocks are viewable based on profile privacy"
  on public.unlocks for select
  using (
    (auth.uid() = user_id)
    OR
    (exists (
      select 1 from public.profiles
      where id = public.unlocks.user_id
      and is_public = true
    ))
  );

-- ■ ポリシー2: 作成 (INSERT) - 本人のみ
create policy "Users can insert own unlocks"
  on public.unlocks for insert
  with check (auth.uid() = user_id);

-- ■ ポリシー3: 更新 (UPDATE) - 本人のみ
create policy "Users can update own unlocks"
  on public.unlocks for update
  using (auth.uid() = user_id);

-- ■ ポリシー4: 削除 (DELETE) - 本人のみ
create policy "Users can delete own unlocks"
  on public.unlocks for delete
  using (auth.uid() = user_id);