-- --------------------------------------------------------
-- 5. Achievement_Tags (中間テーブル)
-- 実績とタグの多対多の紐付けを管理
-- --------------------------------------------------------

create table public.achievement_tags (
  id bigint generated by default as identity primary key,
  
  -- どの実績に (FK)
  achievement_id bigint references public.achievements(id) on delete cascade not null,
  
  -- どのタグを (FK)
  tag_id bigint references public.tags(id) on delete cascade not null,
  
  -- 制約: 同じ実績に同じタグを二重登録させない
  unique(achievement_id, tag_id)
);

-- --------------------------------------------------------
-- インデックス設定 (検索高速化)
-- --------------------------------------------------------

-- 1. 実績詳細画面で「この実績についているタグ一覧」を表示する用
create index idx_achievement_tags_achievement_id on public.achievement_tags(achievement_id);

-- 2. タグ検索画面で「このタグがついた実績一覧」を探す用
create index idx_achievement_tags_tag_id on public.achievement_tags(tag_id);


-- --------------------------------------------------------
-- RLS (Row Level Security) 設定
-- --------------------------------------------------------
alter table public.achievement_tags enable row level security;

-- 閲覧: 全員OK
create policy "Tag links are viewable by everyone"
  on public.achievement_tags for select using (true);

-- 作成: ログインユーザーのみ
-- (厳密な権限管理はUI側またはトリガーで行う前提で、DBレベルでは認証済みなら許可)
create policy "Authenticated users can link tags"
  on public.achievement_tags for insert with check (auth.role() = 'authenticated');